// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimationConfig: typeof import('./src/editor/config-center/animation-config.vue')['default']
    AsideToolbar: typeof import('./src/editor/edit-center/aside-toolbar.vue')['default']
    CanvasContainer: typeof import('./src/editor/edit-center/canvas-container.vue')['default']
    ComponentLayer: typeof import('./src/editor/lib-layer/component-layer.vue')['default']
    ComponentLib: typeof import('./src/editor/lib-layer/component-lib.vue')['default']
    ComponentTemplate: typeof import('./src/editor/edit-center/component-template.vue')['default']
    Editor: typeof import('./src/editor/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EventConfig: typeof import('./src/editor/config-center/event-config.vue')['default']
    LineInsertPlaceholder: typeof import('./src/components/line-insert-placeholder/line-insert-placeholder.vue')['default']
    ModalList: typeof import('./src/editor/edit-center/modal-list.vue')['default']
    PageConfig: typeof import('./src/editor/config-center/page-config.vue')['default']
    PageList: typeof import('./src/editor/edit-center/page-list.vue')['default']
    PropConfig: typeof import('./src/editor/config-center/prop-config.vue')['default']
    Render: typeof import('./src/render/Render.vue')['default']
    StyleConfig: typeof import('./src/editor/config-center/style-config.vue')['default']
    TopToolbar: typeof import('./src/editor/edit-center/top-toolbar.vue')['default']
    ZhButton: typeof import('./src/components/zh-button/zh-button.vue')['default']
    ZhContainer: typeof import('./src/components/zh-container/zh-container.vue')['default']
    ZhForm: typeof import('./src/components/zh-form/zh-form.vue')['default']
    ZhInput: typeof import('./src/components/zh-input/zh-input.vue')['default']
    ZhSelect: typeof import('./src/components/zh-select/zh-select.vue')['default']
    ZhSvg: typeof import('./src/components/zh-svg/zh-svg.vue')['default']
    ZhTable: typeof import('./src/components/zh-table/zh-table.vue')['default']
  }
}

export { }
