// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./admin/Admin.vue')['default']
    AdminTest: typeof import('./admin/AdminTest.vue')['default']
    AnimationConfig: typeof import('./editor/config-center/animation-config.vue')['default']
    AsideToolbar: typeof import('./editor/edit-center/aside-toolbar.vue')['default']
    ComponentLayer: typeof import('./editor/component-center/component-layer.vue')['default']
    ComponentLib: typeof import('./editor/component-center/component-lib.vue')['default']
    Container: typeof import('./components/container/container.vue')['default']
    Editor: typeof import('./editor/Editor.vue')['default']
    EditorTemplate: typeof import('./editor/edit-center/editor-template.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElevatedButton: typeof import('./components/button/elevated-button/elevated-button.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    EventConfig: typeof import('./editor/config-center/event-config.vue')['default']
    Fab: typeof import('./components/button/fab/fab/fab.vue')['default']
    FilledTextField: typeof import('./components/text-field/filled-text-field/filled-text-field.vue')['default']
    Form: typeof import('./components/form/form.vue')['default']
    LineInsertPlaceholder: typeof import('./editor/edit-center/child/line-insert-placeholder.vue')['default']
    Modal: typeof import('./components/modal/modal.vue')['default']
    ModalList: typeof import('./editor/edit-center/modal-list.vue')['default']
    OutlinedTextField: typeof import('./components/text-field/outlined-text-field/outlined-text-field.vue')['default']
    PageConfig: typeof import('./editor/config-center/page-config.vue')['default']
    PageList: typeof import('./editor/edit-center/page-list.vue')['default']
    PropConfig: typeof import('./editor/config-center/prop-config.vue')['default']
    Render: typeof import('./render/Render.vue')['default']
    RenderTemplate: typeof import('./render/render-template.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleConfig: typeof import('./editor/config-center/style-config.vue')['default']
    Switch: typeof import('./components/switch/switch.vue')['default']
    Temp: typeof import('./admin/temp.vue')['default']
    TopToolbar: typeof import('./editor/edit-center/top-toolbar.vue')['default']
    ZhSvg: typeof import('./components/zh-svg/zh-svg.vue')['default']
  }
}
