// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    ZhButton: typeof import('./src/components/zh-button/zh-button.vue')['default']
    ZhInput: typeof import('./src/components/zh-input/zh-input.vue')['default']
    ZhSelect: typeof import('./src/components/zh-select/zh-select.vue')['default']
  }
}

export { }
